<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="MSTest" Version="4.3.3" />
    <PackageVersion Include="WixToolset.UI.wixext" Version="6.0.2" />
  </ItemGroup>
</Project>
