<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>LibraTray.Core.Tests</AssemblyName>
    <RootNamespace>LibraTray.Core.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\LibraTray.Core\LibraTray.Core.csproj" />
  </ItemGroup>
</Project>
